import { OverlayTemplate } from "../schema";

export const checklistCard: OverlayTemplate = {
  id: "checklist-card",
  name: "Checklist Card",
  category: "Productivity",
  tags: ["checklist", "todo", "tips", "guide", "actionable"],
  canvas: { width: 1000, height: 1500 },
  layers: [
    // Header section
    {
      id: "header",
      type: "shape",
      shape: "rectangle",
      x: 0,
      y: 0,
      w: 1000,
      h: 300,
      fill: "#6366f1"
    },
    // Title
    {
      id: "title",
      type: "text",
      x: 80,
      y: 80,
      w: 840,
      h: 140,
      text: "5 THINGS TO DO\nTHIS WEEK",
      fontFamily: "system-ui",
      fontWeight: 900,
      fontSize: 56,
      lineHeight: 1.2,
      letterSpacing: 1,
      align: "center",
      color: "#ffffff"
    },
    // Checklist background
    {
      id: "list-bg",
      type: "shape",
      shape: "rectangle",
      x: 80,
      y: 350,
      w: 840,
      h: 1000,
      fill: "rgba(255,255,255,0.95)",
      radius: 24,
      shadow: "medium"
    },
    // Item 1
    {
      id: "check-1",
      type: "text",
      x: 130,
      y: 420,
      w: 60,
      h: 60,
      text: "✓",
      fontFamily: "system-ui",
      fontWeight: 900,
      fontSize: 48,
      lineHeight: 1,
      letterSpacing: 0,
      align: "center",
      color: "#10b981"
    },
    {
      id: "item-1",
      type: "text",
      x: 210,
      y: 425,
      w: 650,
      h: 50,
      text: "Plan your week ahead",
      fontFamily: "system-ui",
      fontWeight: 600,
      fontSize: 32,
      lineHeight: 1,
      letterSpacing: 0,
      align: "left",
      color: "#1f2937"
    },
    // Item 2
    {
      id: "check-2",
      type: "text",
      x: 130,
      y: 560,
      w: 60,
      h: 60,
      text: "✓",
      fontFamily: "system-ui",
      fontWeight: 900,
      fontSize: 48,
      lineHeight: 1,
      letterSpacing: 0,
      align: "center",
      color: "#10b981"
    },
    {
      id: "item-2",
      type: "text",
      x: 210,
      y: 565,
      w: 650,
      h: 50,
      text: "Exercise 30 minutes",
      fontFamily: "system-ui",
      fontWeight: 600,
      fontSize: 32,
      lineHeight: 1,
      letterSpacing: 0,
      align: "left",
      color: "#1f2937"
    },
    // Item 3
    {
      id: "check-3",
      type: "text",
      x: 130,
      y: 700,
      w: 60,
      h: 60,
      text: "✓",
      fontFamily: "system-ui",
      fontWeight: 900,
      fontSize: 48,
      lineHeight: 1,
      letterSpacing: 0,
      align: "center",
      color: "#10b981"
    },
    {
      id: "item-3",
      type: "text",
      x: 210,
      y: 705,
      w: 650,
      h: 50,
      text: "Read for 15 minutes",
      fontFamily: "system-ui",
      fontWeight: 600,
      fontSize: 32,
      lineHeight: 1,
      letterSpacing: 0,
      align: "left",
      color: "#1f2937"
    },
    // Item 4
    {
      id: "check-4",
      type: "text",
      x: 130,
      y: 840,
      w: 60,
      h: 60,
      text: "✓",
      fontFamily: "system-ui",
      fontWeight: 900,
      fontSize: 48,
      lineHeight: 1,
      letterSpacing: 0,
      align: "center",
      color: "#10b981"
    },
    {
      id: "item-4",
      type: "text",
      x: 210,
      y: 845,
      w: 650,
      h: 50,
      text: "Meal prep Sunday",
      fontFamily: "system-ui",
      fontWeight: 600,
      fontSize: 32,
      lineHeight: 1,
      letterSpacing: 0,
      align: "left",
      color: "#1f2937"
    },
    // Item 5
    {
      id: "check-5",
      type: "text",
      x: 130,
      y: 980,
      w: 60,
      h: 60,
      text: "✓",
      fontFamily: "system-ui",
      fontWeight: 900,
      fontSize: 48,
      lineHeight: 1,
      letterSpacing: 0,
      align: "center",
      color: "#10b981"
    },
    {
      id: "item-5",
      type: "text",
      x: 210,
      y: 985,
      w: 650,
      h: 50,
      text: "Call a friend",
      fontFamily: "system-ui",
      fontWeight: 600,
      fontSize: 32,
      lineHeight: 1,
      letterSpacing: 0,
      align: "left",
      color: "#1f2937"
    }
  ]
};
